const ActionTypes = {
    VIDEO_PLAY: 'v_play',
    VIDEO_PAUSE: 'v_pause',
    VIDEO_STOP: 'v_stop',
    VIDEO_RELOAD: 'v_reload',
    VIDEO_VOLUME_UP: 'v_volume_up',
    VIDEO_VOLUME_DOWN: 'v_volume_down',
    VIDEO_VOLUME_CHANGE: 'v_volume_change',
    VIDEO_TOGGLE_MUTE: 'v_toggle_mute',
    VIDEO_LIKE: 'v_like',
    VIDEO_UNLIKE: 'v_unlike',
    VIDEO_TIME_CHANGE: 'v_time_change',
    VIDEO_SELECT: 'v_list_select',
    VIDEO_SOURCE_CHANGE: 'v_source_change',
    VIDEO_DURATION_CHANGE: 'v_duration_change',
    VIDEO_LIST_CHANGE: 'v_list_change',
    VIDEO_LAUNCH: 'v_launch',
    VIDEO_SAVE_STATE: 'v_save_state',
    EDITOR_TITLE_CHANGE: 'e_title_change',
    EDITOR_URL_CHANGE: 'e_url_change',
    EDITOR_FORM_VALIDATE: 'e_form_validate',
    VIDEO_ADD: 'v_add',
    VIDEO_DELETE: 'v_delete',
    VIDEO_APPROVE: 'v_approve',
    VIDEO_UPDATE: 'v_update',
    VIDEO_PREPARE_EDIT: 'v_prepare_edit',
    VIDEO_RESET_FORM: 'v_reset_form',
    ALERT_SHOW: 'alert_show',
    ALERT_DISMISS: 'alert_dismiss',
    MODAl_SHOW: 'modal_show',
    MODAl_DISMISS: 'modal_dismiss',
}

export default ActionTypes